### ISSUE TITLE
4.27

### ISSUE THREAD

**Issue by marshal-it** [nakdeyes/UnrealImGuiTools#3]
i want 4.27 version

**Comment by nakdeyes** [comment]
@marshal-it - Sorry, I just saw this message! 

I really want this to be compatible with 4.XX. It can work there with very minimal changes ( I built most of it in 4.XX then upgraded it to 5.X )

I will bump up priority of getting the 4.XX version going again!

**Comment by nakdeyes** [comment]
@marshal-it. Ask and you shall receive! 😎 . I just submitted a change with commit 9f23359e3180d98708f4a083ff4750abfc50feed to the master branch, that formally supports both UE 4.XX and 5.XX !! 

Enjoy and let me know if you run into any other issues.

**Comment by nakdeyes** [comment]
Add wtih 9f23359e3180d98708f4a083ff4750abfc50feed
