### ISSUE TITLE
Build Problem due to Optimzation Flags being modified

### ISSUE THREAD

**Issue by a-najafi** [nakdeyes/UnrealImGuiTools#5]
I have added this plugin to my project and get this error during build

 Module.ImGuiTools.cpp(11): [C4426] optimization flags changed after including header, may be due to #pragma optimize()

I am using UnrealImgui from this fork
[https://github.com/IDI-Systems/UnrealImGui](https://github.com/IDI-Systems/UnrealImGui)

**Comment by klechenov** [comment]
I created PR - https://github.com/nakdeyes/UnrealImGuiTools/pull/6

**Comment by nakdeyes** [comment]
@a-najafi - Sorry about the issue. luckily @klechenov has your back with a fix and I have just merged it in. 

Curious if you can provide for my own knowledge: what platform and build spec you are using? I am attempting to find out where #pragma optimize is not allowed 😬

**Comment by klechenov** [comment]
For me - Development Editor and Development Game.  Everything is ok with others, including Shipping

**Comment by a-najafi** [comment]
@klechenov @nakdeyes Thank you both 🙏
